steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/my-docker-repo/myimage',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/my-docker-repo/myimage']
serviceAccount: 'projects/neurolake-marketing-gcp-homol/serviceAccounts/teste-deploy@neurolake-marketing-gcp-homol.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY