steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/images/teste:$TAG_NAME',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/images/teste:$TAG_NAME']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'teste'
    - '--image'
    - 'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/images/teste:$TAG_NAME'
    - '--region'
    - 'us-central1'
images:
- 'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/images/teste:$TAG_NAME'
options:
  logging: CLOUD_LOGGING_ONLY

#BASE PARA CRIAÇÃO DA AUTOMAÇÃO
# steps:
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/PROJECT_ID/IMAGE', '.']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/PROJECT_ID/IMAGE']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/PROJECT_ID/IMAGE', '--region', 'REGION']
# images:
# - gcr.io/PROJECT_ID/IMAGE