# steps:
#   # Docker Build
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t',
#            'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/my-docker-repo/myimage',
#            '.']

#   # Docker Push
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push',
#            'us-central1-docker.pkg.dev/neurolake-marketing-gcp-homol/my-docker-repo/myimage']
# serviceAccount: 'projects/neurolake-marketing-gcp-homol/serviceAccounts/teste-deploy@neurolake-marketing-gcp-homol.iam.gserviceaccount.com'
# options:
#   logging: CLOUD_LOGGING_ONLY

steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/neurolake-marketing-gcp-homol/demo-app:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/neurolake-marketing-gcp-homol/demo-app:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'demo-app'
  - '--image'
  - 'gcr.io/neurolake-marketing-gcp-homol/demo-app:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/neurolake-marketing-gcp-homol/demo-app:$COMMIT_SHA'
serviceAccount: 'projects/neurolake-marketing-gcp-homol/serviceAccounts/teste-deploy@neurolake-marketing-gcp-homol.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY